services:
  #frontend service
  frontend:
    container_name: frontend
    image: frontend:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    environment:
      - SERVER_HOST=host.docker.internal
      - SERVER_PORT=8080
    depends_on:
      - backend

  # backend service
  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 8080:8080
    